app:
  log_level: info
feasibility:
  base_url: https://feasibility.diz.uni-marburg.de/query/execute
  auth:
    basic:
      user:
      password:
broker:
  url:
#  auth:
#    client_credentials:
#      token_url:
#      client_id:
#      client_secret:
