services:

  translate:
    image: ghcr.io/diz-unimr/translate:1.2.1
    environment:
      cql.ontology.pkg.version: 4.1.0
      cql.ontology.pkg.credentials.user: ${GITLAB_PACKAGE_USER}
      cql.ontology.pkg.credentials.password: ${GITLAB_PACKAGE_PASSWORD}
    ports:
      - "8081:8080"

  fhir-server:
    image: samply/blaze:1.10.1
    environment:
      BASE_URL: "http://localhost:8080"
      JAVA_TOOL_OPTIONS: "-Xmx4g"
      LOG_LEVEL: debug
      ENFORCE_REFERENTIAL_INTEGRITY: "false"
    ports:
      - "8080:8080"

  backend:
    image: ghcr.io/diz-unimr/machbarkeit-backend:1.2.11
    restart: unless-stopped
    environment:
      - LOG_LEVEL=debug
      - BASE_URL=http://localhost:3000
      - AUTH__OIDC__ISSUER_URL
      - AUTH__OIDC__CLIENT_ID
      - AUTH__OIDC__CLIENT_SECRET
      - CORS__ALLOW_ORIGIN=http://localhost:5173
      - SESSION__CROSS_DOMAIN=false
      - MDR__ENDPOINT=https://mdr.diz.uni-marburg.de/api
      - DATABASE__URL=sqlite://db.sqlite?mode=rwc
    ports:
      - "3000:3000"
